name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - name: Build
        run: npm run marzban:build
      - uses: actions/configure-pages@v2
      - name: Copy files to /marzban path
        run: |
          mkdir -p dist/marzban
          cp -r marzban/.vitepress/dist/* dist/marzban
      - uses: actions/upload-pages-artifact@v4
        with:
          path: dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
